site_name: quotonic
repo_url: https://github.com/jewaniuk/quotonic
site_url: ""
site_description: A platform for performing efficient simulations of nonlinear quantum photonic circuits.
site_author: Jacob Ewaniuk
edit_uri: edit/main/docs/
repo_name: jewaniuk/quotonic
copyright: Maintained by <a href="https://www.linkedin.com/in/jacobewaniuk/">Jacob Ewaniuk</a>.
use_directory_urls: false

nav:
  - fock: fock.md
  - clements: clements.md
  - aa: aa.md
  - nl: nl.md
  - qpnn: qpnn.md
  - trainer: trainer.md
  - training_sets: training_sets.md
  - perm: perm.md
  - logic: logic.md
  - utils: utils.md
  - types: types.md

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            extra:
              show_object_full_path: true
              show_module_path: true
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jewaniuk/quotonic
    - icon: fontawesome/brands/python
      link: https://pypi.com/project/quotonic

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - js/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css

#extra_javascript:
#  - https://polyfill.io/v3/polyfill.min.js?features=es6
#  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js