site_name: quotonic
repo_url: https://github.com/jewaniuk/quotonic
site_url: ""
site_description: A platform for performing efficient simulations of nonlinear quantum photonic circuits.
site_author: Jacob Ewaniuk
edit_uri: edit/main/docs/
repo_name: jewaniuk/quotonic
copyright: Maintained by <a href="https://www.linkedin.com/in/jacobewaniuk/">Jacob Ewaniuk</a>.
use_directory_urls: false

nav:
  - fock: fock.md
  - clements: clements.md
  - aa: aa.md
  - nl: nl.md
  - qpnn: qpnn.md
  - trainer: trainer.md
  - training_sets: training_sets.md
  - perm: perm.md
  - logic: logic.md
  - utils: utils.md
  - types: types.md

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            members_order: source
            group_by_category: false
            show_root_toc_entry: false
            extra:
              show_object_full_path: true
              show_module_path: true
  - mike
theme:
  name: material
  feature:
    tabs: true
  features:
    - navigation.sections
    - navigation.tracking
    - toc.integrate                 # keeps on-page ToC integrated
    - navigation.instant
    - navigation.top
    - navigation.tabs
    - navigation.prune
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  highlightjs: true

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jewaniuk/quotonic
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/quotonic

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - codehilite
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences

extra_javascript:
  - js/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
  - styles/extra.css