name: docs

on:
  push:
    branches:
      - main
      - jax
  pull_request:
    types:  [opened, synchronize, reopened]

jobs:
  docs:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout quotonic
        uses: actions/checkout@v4

      - name: Prepare Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]

      - name: Check Documentation Build
        run: mkdocs build -s