name: release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version tag to release (e.g. v1.2.3)"
        required: true
        type: string

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout quotonic
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed so 'mike' can access history

      - name: prepare python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install twine .[dev]

      - name: build package
        run: python -m build

      - name: publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

      - name: deploy versioned docs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          version=${{ github.event.inputs.version }}
          mike deploy --push --update-aliases $version latest
