name: release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "version to release (e.g. 1.2.3)"
        required: true
        type: string

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout quotonic
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: prepare python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install twine .[dev]

      - name: build package
        run: python -m build

      - name: publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          attestations: true
          skip-existing: true

      - name: deploy versioned docs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          version=v${{ github.event.inputs.version }}
          mike deploy $version latest --push --update-aliases

      - name: create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: quotonic ${{ github.event.inputs.version }}
          body: |
            This release corresponds to version ${{ github.event.inputs.version }} on PyPI.
            See documentation for this version at
            https://jewaniuk.github.io/quotonic/v${{ github.event.inputs.version }}/.
